drop table if exists member;
create table member (
    id          bigint generated by default as identity (start with 13) primary key,
    firstname   varchar(225),
    lastname    varchar(225),
    email       varchar(225),
    password    varchar(255),
    photo       varchar(45),
    enabled     boolean default false not null,
    createdOn   timestamp,
    modifiedOn  timestamp,
    createdBy   varchar(45),
    modifiedBy  varchar(45)
);

drop table if exists roles;
create table roles (
   id          bigint generated by default as identity (start with 1) primary key,
   name        varchar(225),
   description varchar(225),
   createdOn   timestamp,
   modifiedOn  timestamp,
   createdBy   varchar(45),
   modifiedBy  varchar(45)
);

drop table if exists member_roles;
create table member_roles (
      users_id   bigint,
      roles_id   bigint
);

alter table member add constraint email_unique unique(email);

drop table if exists challenge;
create table challenge (
       challenge_id bigint generated by default as identity (start with 2) primary key,
       title        varchar(225),
       description  varchar(225),
       challengeowner bigint,
       createdOn    timestamp,
       modifiedOn   timestamp,
       createdBy    varchar(45),
       modifiedBy   varchar(45)
);

alter table challenge add foreign key (challengeowner) REFERENCES member (id);

drop table if exists question_set;
create table question_set (
      id             bigint generated by default as identity (start with 5) primary key,
      question       varchar(425),
      answer1        varchar(225),
      answer2        varchar(225),
      answer3        varchar(225),
      answer4        varchar(225),
      correctOptions varchar(225),
      challenge_id   bigint
);

drop table if exists game;
create table game (
      game_id     bigint generated by default as identity (start with 1) primary key,
      pin         varchar(225),
      gameStatus  varchar(225),
      challengeId varchar(225),
      createdOn   timestamp,
      modifiedOn  timestamp
);

drop table if exists current_game_session;
create table current_game_session (
      id                   bigint generated by default as identity (start with 1) primary key,
      pin                  varchar(225) not null unique,
      moderator            varchar(225) not null,
      users_json           text,
      questions_json       text,
      current_question_no  int,
      scores_json          text
);





