create table member (
    id          bigint generated by default as identity (start with 2) primary key,
    firstname   varchar(225),
    lastname    varchar(225),
    email       varchar(225),
    password    varchar(255),
    photo       varchar(45),
    enabled     boolean default false not null,
    createdOn   datetime,
    modifiedOn  datetime,
    createdBy   varchar(45),
    modifiedBy  varchar(45)
);

create table roles (
    id          bigint generated by default as identity (start with 1) primary key,
    name        varchar(225),
    description varchar(225),
    createdOn   datetime,
    modifiedOn  datetime,
    createdBy   varchar(45),
    modifiedBy  varchar(45)
);

create table member_roles (
    users_id   bigint,
    roles_id   bigint
);

create table challenge (
    challenge_id bigint generated by default as identity (start with 2) primary key,
    title        varchar(225),
    description  varchar(225),
    challengeowner bigint,
    createdOn    datetime,
    modifiedOn   datetime,
    createdBy    varchar(45),
    modifiedBy   varchar(45)
);

alter table challenge add foreign key (challengeowner) REFERENCES member (id);

create table question_set (
    id             bigint generated by default as identity (start with 5) primary key,
    question       varchar(425),
    answer1        varchar(225),
    answer2        varchar(225),
    answer3        varchar(225),
    answer4        varchar(225),
    correctOptions varchar(225),
    challenge_id   bigint
);

create table game (
    game_id     bigint generated by default as identity (start with 1) primary key,
    pin         varchar(225),
    gameStatus  varchar(225),
    challengeId varchar(225),
    createdOn   datetime,
    modifiedOn  datetime
);





