create table user
(
    id         bigint generated by default as identity (start with 1) primary key,
    username   varchar(225),
    password   varchar(255),
    role       varchar(45),
    createdOn  datetime,
    modifiedOn datetime,
    createdBy  varchar(45),
    modifiedBy varchar(45)
);
create table role
(
    id         bigint generated by default as identity (start with 1) primary key,
    name       varchar(225),
    createdOn  datetime,
    modifiedOn datetime,
    createdBy  varchar(45),
    modifiedBy varchar(45)
);
create table user_roles
(
    id         bigint generated by default as identity (start with 1) primary key,
    users_id   bigint,
    roles_id   bigint,
    name       varchar(225),
    createdOn  datetime,
    modifiedOn datetime,
    createdBy  varchar(45),
    modifiedBy varchar(45)
);

create table challenge
(
    challenge_id bigint generated by default as identity (start with 1) primary key,
    title        varchar(225),
    description  varchar(225),
    createdOn    datetime,
    modifiedOn   datetime,
    createdBy    varchar(45),
    modifiedBy   varchar(45)
);


create table question_set
(
    id             bigint generated by default as identity (start with 1) primary key,
    question       varchar(425),
    answer1        varchar(225),
    answer2        varchar(225),
    answer3        varchar(225),
    answer4        varchar(225),
    correctOptions varchar(225),
    challenge_id   bigint
);

create table game
(
    game_id     bigint generated by default as identity (start with 1) primary key,
    pin         varchar(225),
    gameStatus  varchar(225),
    challengeId varchar(225),
    createdOn   datetime,
    modifiedOn  datetime
);